services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:alpine3.20
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 2

  fastapi:
    container_name: ${PROJECT_NAME}-fastapi
    build: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:8000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
